### ISSUE TITLE
feature request - orientation toggle

### ISSUE THREAD

**Issue by stiivgiaco** [pgaskin/NickelMenu#67]
First of all i wanted to say thank you for taking your time to develop this and well done. I have a small feature request if possible please.

I have added the ForceAllowLandscape=true parameter in the kobo config file which enabled portrait or landscape mode,  but i would also like to have inverted landscape and inverted portrait as an option also as an option. This seems to be possible to do so as it is found in the Developer options menu. 

Would it be possible to have a rotation flag added please? or even the possibility of adding the Developer options section in the home screen?

Thanks in advance, 
STiiVO

**Comment by pgaskin** [comment]
Some notes for myself:
- `QGuiApplication::primaryScreen()->orientationChanged` changes the orientation of the output (I'm assuming it's passed to KoboScreenNXP::setOrientation and does the ioctl on the FB), but not of the app itself or the touchscreen.

**Comment by NiLuJe** [comment]
> 
>     * Most orientation changing stuff does something funny with the orientation sensors, but I haven't looked into whether it will be necessary for this action.
> 

That's... weird.

For reference, on a device w/ a gyro, the gyro sends raw evdev events to a dedicated device (event2) but I don't think *anyone* consumes those in userspace. Instead, the ntx_io driver sends synthetic "I've rotated!" events to event0., and those are pretty-much rotation-independent, so I'm not *quite* sure what fiddling would be entailed here. 

```
-- For the events of the Forma accelerometer (MSC.value)
local MSC_RAW_GSENSOR_PORTRAIT_DOWN = 0x17
local MSC_RAW_GSENSOR_PORTRAIT_UP = 0x18
local MSC_RAW_GSENSOR_LANDSCAPE_RIGHT = 0x19
local MSC_RAW_GSENSOR_LANDSCAPE_LEFT = 0x1a
-- Not that we care about those, but they are reported, and accurate ;).
local MSC_RAW_GSENSOR_BACK = 0x1b
local MSC_RAW_GSENSOR_FRONT = 0x1c
```

There *is* an ntxio ioctl to (I suppose, I never bothered to test that) toggle said synthetic events, though.

**Comment by pgaskin** [comment]
> That's... weird ...
> ... so I'm not quite sure what fiddling would be entailed here

By "something funny", I was referring to that it does something to do with enabling/disabling the sensor, setting some global variables, and setting the rotation mask when the different locked modes are selected.

> the gyro sends raw evdev events to a dedicated device

From the firmware, it appears that the MMA8652 and KS1226 classes access the sensors directly (and Nickel reads the value and uses `QWindowSystemInterface::handleScreenOrientationChange` to trigger the actual logic for handling it). This really belongs in the QPA, but Kobo probably put it directly into Nickel rather than libkobo for simplicity (it helps that they control Qt, so they don't need to worry about source/binary compatibility with the private QPA APIs).

For the MMA8652 sensor, `/sys/devices/virtual/input/input2/pl_cfg` is used to configure the parameters, and other files under `/sys/devices/virtual/input/input2/` are used to read the sensor state.

**Comment by NiLuJe** [comment]
Huh, so they do consume the raw events!

**Comment by pgaskin** [comment]
> Huh, so they do consume the raw events

The state is read from sysfs:

MMA8652: `/sys/devices/virtual/input/input2/stick_status`, `/sys/devices/virtual/input/input2/pl_bf_zcomp`, whatever `QOrientationSensor::reading` reads.
KX122: `/sys/devices/platform/soc/2100000.aips-bus/21a0000.i2c/i2c-0/0-001e/input/input2/tilt_angle_ll`, `/sys/devices/platform/soc/2100000.aips-bus/21a0000.i2c/i2c-0/0-001e/input/input2/tilt_angle_hl`.

**Comment by NiLuJe** [comment]
Huh. then the magic probably happens in `QOrientationSensor::reading`, and it probably does rely on the ntxio synthetic events, because `stick_status` is stuck to `Normal` over here, and the zcomp too (to `0xc5`).

**Comment by pgaskin** [comment]
IIRC, stick_status is for if the sensor is literally stuck (the MMA sensor is known to have an issue with the z-axis sticking).
