### ISSUE TITLE
Cannot exit Web Browser in 4.23.15505

### ISSUE THREAD

**Issue by SilverGreen93** [pgaskin/NickelMenu#86]
On my Kobo Forma for example, if I use the NickelMenu to open the Web browser, I now cannot close it unless I restart my device because it starts in full screen and no back or quit button is available.

When started from the Beta features menu, the web browser starts in a pop-up window with back and close buttons.

**Comment by pgaskin** [comment]
This is a known issue due to firmware changes:

https://github.com/pgaskin/NickelMenu/blob/6a23d1c12e9cede5defee6b243f177fdff026b09/res/doc#L35

As a workaround, you can either use the `modal` option to make it appear the same way as when you access it from the "Beta Features" dialog, or you can add a menu item like `menu_item:browser:Quit:nickel_misc:home` to be able to exit the browser.

**Comment by SilverGreen93** [comment]
Thanks. It works now. You should have mentioned it as a breaking change or something like that in the release comments. :)
