### ISSUE TITLE
cmd_output action not displaying newlines

### ISSUE THREAD

**Issue by jackiew1** [pgaskin/NickelMenu#92]
@pgaskin As per your suggestion I'm creating this issue (minor) for you to look at if/when you have the time and inclination.

Details at [https://www.mobileread.com/forums/showpost.php?p=4042416&postcount=317](url) posts #317-324

**Comment by pgaskin** [comment]
This would be due to `_ZN6QLabel13setTextFormatEN2Qt10TextFormatE` being called for the ConfirmationDialog text with a value of 0x1 (`Qt::RichText`), which causes the text to be interpreted as HTML. I'm not sure if this was the behaviour in previous firmware versions.

This should be fixable by using `Qt::convertFromPlainText` with `Qt::WhiteSpacePre`.

**Comment by shermp** [comment]
I kind of like the HTML formatted text. Makes it easy to do simple bold/italics, so I probably won't change it for NickelDBus, although maybe I need to note it in the documentation.
